// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using CalliAPI.Models.AmourgisDB;
using Microsoft.EntityFrameworkCore;
using CalliAPI.Models.AmourgisDB.BankruptcySchema;
using CalliAPI.Models.AmourgisDB.PersonalInjurySchema;
using CalliAPI.Models.AmourgisDB.ClioSchema;
using CalliAPI.Models.AmourgisDB.dboSchema;

namespace CalliAPI.DataAccess;

/// <summary>
/// AmourgisDBContext is the database context for the Amourgis database.
/// </summary>
public partial class AmourgisDBContext : DbContext
{
    /// <summary>
    /// The constructor for the AmourgisDBContext class.
    /// </summary>
    /// <param name="options"></param>
    public AmourgisDBContext(DbContextOptions<AmourgisDBContext> options)
        : base(options)
    {
    }

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
    public virtual DbSet<CaseInformation> CaseInformation { get; set; }

    public virtual DbSet<CrashReports> CrashReports { get; set; }

    public virtual DbSet<DebtorInformation> DebtorInformation { get; set; }

    public virtual DbSet<Documents> Documents { get; set; }

    public virtual DbSet<Jurisdictions> Jurisdictions { get; set; }

    public virtual DbSet<MessageInformation> MessageInformation { get; set; }

    public virtual DbSet<Offices> Offices { get; set; }

    public virtual DbSet<PCLAW> PCLAW { get; set; }

    public virtual DbSet<Payments> Payments { get; set; }

    public virtual DbSet<Staging> Staging { get; set; }

    public virtual DbSet<YesterdayCases> YesterdayCases { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<CaseInformation>(entity =>
        {
            entity.HasKey(e => e.CaseID).HasName("PK__CaseInfo__6CAE526C1E8F078D");
        });

        modelBuilder.Entity<CrashReports>(entity =>
        {
            entity.Property(e => e.CreateTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.VictimGender).IsFixedLength();
        });

        modelBuilder.Entity<DebtorInformation>(entity =>
        {
            entity.HasKey(e => e.DebtorID).HasName("PK__DebtorIn__C47716E6E4FE0547");

            entity.ToTable("DebtorInformation", "Bankruptcy", tb => tb.HasTrigger("di_CleanPhoneNumber"));

            entity.Property(e => e.DoNotText).HasDefaultValue(false);
            entity.Property(e => e.MiddleInitial).IsFixedLength();
            entity.Property(e => e.StateCode).IsFixedLength();
        });

        modelBuilder.Entity<Documents>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Document__3214EC072938086A");

            entity.Property(e => e.Id).ValueGeneratedNever();
        });

        modelBuilder.Entity<Jurisdictions>(entity =>
        {
            entity.HasKey(e => e.JurisdictionID).HasName("PK__Jurisdic__160C65CCC702B0A2");
        });

        modelBuilder.Entity<MessageInformation>(entity =>
        {
            entity.HasKey(e => e.DebtorID).HasName("PK__MessageI__C47716E66470DC62");

            entity.Property(e => e.SentToSkipTrace).HasDefaultValue(false);
        });

        modelBuilder.Entity<Offices>(entity =>
        {
            entity.HasKey(e => e.OfficeID).HasName("PK__Offices__4B61930FDF86ACEC");
        });

        modelBuilder.Entity<YesterdayCases>(entity =>
        {
            entity.ToView("YesterdayCases");

            entity.Property(e => e.StateCode).IsFixedLength();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        if (!optionsBuilder.IsConfigured)
        {
            var connectionString = Properties.Settings.Default.SqlConnectionString;
            optionsBuilder.UseSqlServer(connectionString);
        }
    }

#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member
}